# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: '250921790'

menu:
- {name: 'About', path: '.', url: 'index.html'}
- {name: 'Publications', path: 'menu', url: 'publications.html'}
- {name: 'Projects', path: 'menu', url: 'projects.html'}
- {name: 'News', path: 'menu', url: 'news.html'}
- {name: 'Links', path: 'menu', url: 'links.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/walterbircher'}
- {icon: 'graduation-cap', link: 'https://scholar.google.com/citations?user=dzRmhtAAAAAJ&hl=en&oi=ao'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/walter-bircher-17645042/'}
- {icon: 'envelope', link: 'mailto: walter.bircher@yale.edu'}
#- {icon: 'rss-square', link: '/feed.xml'}

# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
